// lib/medical_advices.dart

final List<String> medicalAdvices = [
  "Drink a glass of water right after waking up to activate your internal organs and boost early morning energy.",
  "Keep your bedroom cool and completely dark to improve the quality of your deep sleep cycles tonight.",
  "Look away from your screen every 20 minutes at an object 20 feet away to prevent digital eye strain.",
  "Position your computer screen at eye level to avoid chronic neck strain and upper back stiffness.",
  "Chew your food thoroughly to aid smoother digestion and prevent uncomfortable stomach bloating or gas.",
  "Take the stairs instead of the elevator whenever possible to easily build your daily cardiovascular strength.",
  "Floss your teeth daily; brushing alone leaves nearly 40 percent of your tooth surfaces completely untouched.",
  "Spend ten minutes in natural morning sunlight to properly regulate your body's internal sleep-wake clock.",
  "Cut down on sugary carbonated drinks and replace them with herbal teas or fresh fruit-infused water.",
  "Sanitize your smartphone screen regularly, as it often carries more bacteria than a typical household surface.",
  "Take three slow, deep abdominal breaths when feeling overwhelmed to instantly lower your heart rate and cortisol.",
  "Avoid eating heavy or greasy meals at least three hours before bed to prevent disruptive nighttime acid reflux.",
  "Stand up and pace around during phone calls to easily break up long, unhealthy periods of sitting down.",
  "Apply sunscreen even on cloudy winter days to protect your skin cells from aging ultraviolet radiation.",
  "Avoid cracking your neck forcefully; instead, gently roll your shoulders back to safely relieve built-up stress.",
  "Include diverse colors of vegetables on your dinner plate to ensure you consume a wide mix of essential vitamins.",
  "Avoid consuming caffeine after 2:00 PM so it does not interfere with your nervous system's evening wind-down.",
  "Choose supportive, cushioned footwear over stylish flat shoes if you plan to walk or stand for over an hour.",
  "Open your room windows for ten minutes daily to refresh indoor air quality and flush out stagnant allergens.",
  "Laughing often improves blood vessel function and blood flow, meaning happiness is genuinely healthy for your heart.",
  "Gently stretch your calves and hamstrings before going to bed to prevent painful leg cramps during the night.",
  "Disconnect from all digital devices 30 minutes before sleeping to allow your brain to produce melatonin naturally.",
  "Try learning a small new skill, word, or puzzle weekly to challenge your brain and keep memory sharp.",
  "Use natural herbs and spices like garlic or lemon juice instead of adding extra salt to your cooked meals.",
  "Drink a full glass of water 15 minutes before a meal to naturally prevent overeating by signaling fullness earlier.",
  "Never use hot water on a fresh skin burn; always use cool, running tap water for ten minutes immediately.",
  "Bend your knees and use your legs when lifting heavy objects from the floor to protect your lower back muscles.",
  "A brisk 15-minute walk right after dinner can significantly lower your blood sugar spikes after eating.",
  "Call or meet a close friend today; staying socially active lowers stress hormones and improves mental resilience.",
  "Never ignore persistent, localized pain; it is your body's alarm system telling you something requires professional attention."
];