final List<Map<String, dynamic>> doctors = [
  {
    "first_name": "John",
    "last_name": "Smith",
    "username": "drjohnsmith",
    "email": "john.smith@example.com",
    "password": "hashed_password_123",
    "role": "doctor",
    "phone": "+1234567890",
    "gender": "Male",
    "date_of_birth": "1980-05-14",
    "specialty": "Cardiology"
  },
  {
    "first_name": "Emma",
    "last_name": "Johnson",
    "username": "dremmaj",
    "email": "emma.johnson@example.com",
    "password": "hashed_password_456",
    "role": "doctor",
    "phone": "+1234567891",
    "gender": "Female",
    "date_of_birth": "1985-09-22",
    "specialty": "Neurology"
  },
  {
    "first_name": "Michael",
    "last_name": "Brown",
    "username": "drbrown",
    "email": "michael.brown@example.com",
    "password": "hashed_password_789",
    "role": "doctor",
    "phone": "+1234567892",
    "gender": "Male",
    "date_of_birth": "1978-03-10",
    "specialty": "Dermatology"
  },
  {
    "first_name": "Olivia",
    "last_name": "Davis",
    "username": "drolivia",
    "email": "olivia.davis@example.com",
    "password": "hashed_password_321",
    "role": "doctor",
    "phone": "+1234567893",
    "gender": "Female",
    "date_of_birth": "1990-12-01",
    "specialty": "Pediatrics"
  },
  {
    "first_name": "William",
    "last_name": "Miller",
    "username": "drwmiller",
    "email": "william.miller@example.com",
    "password": "hashed_password_654",
    "role": "doctor",
    "phone": "+1234567894",
    "gender": "Male",
    "date_of_birth": "1975-07-18",
    "specialty": "Orthopedics"
  },
  {
    "first_name": "Sophia",
    "last_name": "Wilson",
    "username": "drsophia",
    "email": "sophia.wilson@example.com",
    "password": "hashed_password_987",
    "role": "doctor",
    "phone": "+1234567895",
    "gender": "Female",
    "date_of_birth": "1988-11-30",
    "specialty": "Gynecology"
  },
  {
    "first_name": "James",
    "last_name": "Moore",
    "username": "drjmoore",
    "email": "james.moore@example.com",
    "password": "hashed_password_147",
    "role": "doctor",
    "phone": "+1234567896",
    "gender": "Male",
    "date_of_birth": "1982-04-25",
    "specialty": "Psychiatry"
  },
  {
    "first_name": "Isabella",
    "last_name": "Taylor",
    "username": "drisabella",
    "email": "isabella.taylor@example.com",
    "password": "hashed_password_258",
    "role": "doctor",
    "phone": "+1234567897",
    "gender": "Female",
    "date_of_birth": "1992-06-15",
    "specialty": "Ophthalmology"
  },
  {
    "first_name": "Benjamin",
    "last_name": "Anderson",
    "username": "drbanderson",
    "email": "ben.anderson@example.com",
    "password": "hashed_password_369",
    "role": "doctor",
    "phone": "+1234567898",
    "gender": "Male",
    "date_of_birth": "1979-01-08",
    "specialty": "Oncology"
  },
  {
    "first_name": "Mia",
    "last_name": "Thomas",
    "username": "drmia",
    "email": "mia.thomas@example.com",
    "password": "hashed_password_159",
    "role": "doctor",
    "phone": "+1234567899",
    "gender": "Female",
    "date_of_birth": "1987-08-19",
    "specialty": "Radiology"
  },
];
